- name: Build APK
        run: |
          # Заходим в папку с кодом
          [ -d my-truck-app ] && cd my-truck-app
          
          # Удаляем старый битый конфиг, если он есть
          rm -f buildozer.spec
          
          # Создаем новый чистый конфиг
          buildozer init
          
          # Быстро правим конфиг: ставим имя приложения
          sed -i 's/package.name = myapp/package.name = truckapp/' buildozer.spec
          sed -i 's/title = My Application/title = Truck Log/' buildozer.spec
          
          # Запускаем сборку
          buildozer android debug
        env:
          APP_ANDROID_ARCHS: "arm64-v8a"
          ACCEPT_SDK_LICENSE: "y"
